### ISSUE TITLE
android.tools.build:gradle:3.1.0 issues

### ISSUE THREAD

**Issue by NicoToast** [Mobbeel/fataar-gradle-plugin#1]
This plugin can be packed normally in version 3.0.0. But It does not work properly in version 3.1.0.

This is the result of packaging in android.tools.build:gradle:3.1.0:

mylibrary-unspecified.aar
---libs
&nbsp;&nbsp;&nbsp;&nbsp;---base.jar
&nbsp;&nbsp;&nbsp;&nbsp;---gson-2.8.2.jar
&nbsp;&nbsp;&nbsp;&nbsp;---gson-2.8.2-sources.jar
---AndroidManifest.xml

**Comment by oscarcpozas** [comment]
In the last version of Gradle plugin the folder hierarchy has changed and the plugin does not work, we will update the plugin in a few days. Stay tunned.
