### ISSUE TITLE
Internal dependency minify issue

### ISSUE THREAD

**Issue by NicoToast** [Mobbeel/fataar-gradle-plugin#2]
After assemble release task，my main module minify is successfully, but my sub module minify is failed。
I'm sure minifyEnabled is true in sub module build.gradle.
How can I solve the problem?

**Comment by oscarcpozas** [comment]
Problem seems to be with the configuration of Proguard. Exactly what's going wrong? Isn't the task over?

**Comment by NicoToast** [comment]
For example:
mylibrary-unspecified.aar
---libs
    ---base.jar (Proguard noneffective)
    ---common.jar (Proguard noneffective)
---classes.jar (Proguard effective)
---AndroidManifest.xml

mylibrary depend on base and common. In addition, common depend on base.
Now I want to make Proguard effect in base.jar and common.jar.
Thanks for your answer.

**Comment by oscarcpozas** [comment]
Currently, the plugin does not support proguard on external dependencies outside the workspace. It should not be difficult to add proguard to these dependencies, if you want you can send me a PR with this functionality.
