### ISSUE TITLE
Do not support publish generated aar to maven

### ISSUE THREAD

**Issue by bangelua** [Mobbeel/fataar-gradle-plugin#23]
I have a aar lib, call as B.aar here, it dependent another aar, call A.aar. 
your plugin works when assemble locally. 
but after I publish my aar lib B to maven repo via uploadArchives, the B.aar file uploaded on maven server still not contains A.aar.

**Comment by oscarcpozas** [comment]
But if you are generating correctly the AAR in local doesn't depend on this plugin the upload to the artifacts repository. How are you publishing this AAR?

**Comment by oscarcpozas** [comment]
Closed for inactivity
