### ISSUE TITLE
Won't the AAR files that libraries depend on be packaged in?

### ISSUE THREAD

**Issue by lgengsy** [Mobbeel/fataar-gradle-plugin#5]
There is my dependencies   those  aar  file  not found

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
    api 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'

    api(name: 'alisdk-feedback-2.5.0', ext: 'aar')
    api(name: 'securityguardaar3-5.1.81', ext: 'aar')
    api(name: 'doutu_sdk_v1.03', ext: 'aar')

}

**Comment by oscarcpozas** [comment]
This issue is not exposing either an error or a problem, so I close the issue.
