### ISSUE TITLE
What does packagesToInclude do?

### ISSUE THREAD

**Issue by devpascoe** [Mobbeel/fataar-gradle-plugin#8]
Just wondering. Is it necessary? should it specify the package of the library for example: package com.demo.lib; 
packagesToInclude = ['com.demo.lib']

**Comment by oscarcpozas** [comment]
If you have a dependency that has transitive dependencies, by default, they will not be added to the final AAR. If you want to add all transitive dependencies you can do it with **includeAllInnerDependencies** propertie, but if you only want to add one in particular you can specify its package in that array.
I don't know if I explain myself clearly?

**Comment by devpascoe** [comment]
cool. So would you specify the full package name eg com.demo.lib ?

**Comment by oscarcpozas** [comment]
Yes.
